/**
 * Story 2.3 — Assertion token handling (frontend).
 * Token is generated by the backend; we only store it in memory and attach to verifier requests.
 *
 * Security rules:
 * - Never log assertion_token
 * - Never expose token in URL
 * - Store in memory only (no localStorage / cookies)
 * - Clear on expiry or re-auth
 */

let memoryToken: string | null = null;
let memoryExpiresAt: number | null = null;

export const TokenService = {
  /** Store token after successful verify. expiresInSeconds is from response (e.g. 300). */
  setToken(token: string, expiresInSeconds: number): void {
    memoryToken = token;
    memoryExpiresAt = Date.now() + expiresInSeconds * 1000;
  },

  /** Get token if still valid; null if expired or not set. */
  getToken(): string | null {
    if (memoryToken == null || memoryExpiresAt == null) return null;
    if (Date.now() >= memoryExpiresAt) {
      memoryToken = null;
      memoryExpiresAt = null;
      return null;
    }
    return memoryToken;
  },

  /** Expiry time in ms (epoch). Null if no token. */
  getExpiresAt(): number | null {
    return memoryExpiresAt;
  },

  /** True if no token or token has expired. */
  isExpired(): boolean {
    return this.getToken() == null;
  },

  /** Clear token (e.g. on logout, re-auth, or expiry). */
  clear(): void {
    memoryToken = null;
    memoryExpiresAt = null;
  },

  /**
   * Use when calling verifier services: Authorization: Bearer <token>.
   * Returns {} if token missing or expired.
   */
  getAssertionAuthHeader(): Record<string, string> {
    const token = this.getToken();
    if (!token) return {};
    return { Authorization: `Bearer ${token}` };
  },

  /** Seconds until expiry; 0 or negative if expired/missing. For display only. */
  secondsUntilExpiry(): number {
    if (memoryExpiresAt == null) return 0;
    return Math.max(0, Math.round((memoryExpiresAt - Date.now()) / 1000));
  },
};
